## Importing the Packages

In [1]:
import numpy as np

In [2]:
# stoping numpy from displaying numbers with scientific notations, ectend the numbers of charachters we can fit in one line to 100, and rounding to 2.
np.set_printoptions(suppress=True, linewidth=100, precision=2)

## Importing the Data

In [3]:
raw_data = np.genfromtxt(r"H:\Loan project\loan-data.csv", delimiter=";", encoding = "unicode_escape", skip_header= 1, autostrip= True)
raw_data


array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
# How many data points are missing in the raw data ? 
np.isnan(raw_data).sum()

np.int64(88005)

In [5]:
temporary_fill = np.nanmax(raw_data) + 1   # this a temporary fill value which consists of the max +1 to ensure it does not exisit in the data before.
temporary_mean = np.nanmean(raw_data, axis = 0) # calculating the mean for each column(axis = 0).


C:\Users\Hamoud's\AppData\Local\Temp\ipykernel_14276\2942669433.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis = 0) # calculating the mean for each column(axis = 0).


In [6]:
temporary_mean # there is entire columns that have a mean value of nan which suggests that these columns might be entirely consist of strings values and not empty.

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
# getting stats for each column of the raw data the min, max and mean and storing it in an array. why? (we will use it later when filling the missing data for each column)
temporary_stats = np.array([np.nanmin(raw_data, axis=0),temporary_mean, np.nanmax(raw_data,axis=0)])

C:\Users\Hamoud's\AppData\Local\Temp\ipykernel_14276\2656753814.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data, axis=0),temporary_mean, np.nanmax(raw_data,axis=0)])


In [8]:
temporary_stats[0,4]

np.float64(1000.0)

## Splitting the Dataset

### Splitting the Columns

In [9]:
# getting the columns that only contains strings
string_columns = np.argwhere(np.isnan(temporary_mean)).squeeze()
string_columns

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [10]:
# getting the columns that only contain vumeric values
numeric_columns = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
numeric_columns

array([ 0,  2,  4,  6,  7, 13])

### Re-importing the Dataset

In [11]:
loan_data_strings = np.genfromtxt(r"H:\Loan project\loan-data.csv", delimiter=";", encoding = "unicode_escape",
                                  skip_header= 1, autostrip= True, usecols=string_columns, dtype=str)
loan_data_strings


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [12]:
# importing the numeric columns only and using the termporary filling to fill the missing data for the mean time.
loan_data_numeric = np.genfromtxt(r"H:\Loan project\loan-data.csv", delimiter=";", encoding = "unicode_escape",
                                  skip_header= 1, autostrip= True, usecols=numeric_columns, filling_values= temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [13]:
full_header = np.genfromtxt(r"H:\Loan project\loan-data.csv", delimiter=";", encoding = "unicode_escape",
                            skip_footer= raw_data.shape[0], autostrip= True, dtype=str)  #skip_footer = date.shpe[0] this is to keep only the header and ignore the rest of the data
full_header


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
# assigning the headers for its string and numeric datasets.
loan_data_strings_header, loan_data_numeric_header = full_header[string_columns] , full_header[numeric_columns]

In [15]:
loan_data_strings_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [16]:
loan_data_numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [17]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [18]:
checkpoint_test_strings_1= checkpoint("checkoint-test-1",loan_data_strings_header,loan_data_strings)

In [19]:
checkpoint_test_strings_1["header"]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [20]:
np.array_equal(checkpoint_test_strings_1["header"],loan_data_strings_header)

True

## Manipulating String Columns

In [21]:
loan_data_strings_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
loan_data_strings_header[0] = "issue_date"
loan_data_strings_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [24]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
# since all the data is in 2015 we will remove the year and keep only the month, ('' refers to missing issue date in the raw date)
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],"-15")

C:\Users\Hamoud's\AppData\Local\Temp\ipykernel_14276\2197646333.py:2: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],"-15")


In [26]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [27]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [28]:
#converting the months names into numbers
for i in range(13):
        loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                          str(i),  # I have to convert the i to str becuase the array data type is string so if we tried to replace the value with i (int) it will throw error.
                                          loan_data_strings[:,0])

In [29]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [30]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [32]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [33]:
np.unique(loan_data_strings[:,1]).size

9

In [34]:
# categorize loan status into 1 (good) and 0 (Bad).
# first we make an array containing all the loan status that are categorized as bad
loan_satus_bad = np.array(['', 'Charged Off', 'Default','Late (31-120 days)'])

In [35]:
#then we assign the new valus (0,1) to the loan status column as per it's value if it falls in the loan status bad then 0 else 1
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],loan_satus_bad),0,1)

In [36]:
# Making sure that we managed to transform loan status into dummy variables (0,1)
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [37]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [38]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [39]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [40]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2]," months")

C:\Users\Hamoud's\AppData\Local\Temp\ipykernel_14276\833848916.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2]," months")


In [41]:
# after strioing the months from the values in the term column, it would be a good idea to make the column header more descriptive
loan_data_strings_header[2] = "term_months"

In [42]:
#replacing the missing values with 60 months
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '','60',loan_data_strings[:,2])
np.unique(loan_data_strings[:,2])


array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [43]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [44]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [45]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [46]:
# subsgrade consists of the grade + a degree from 1 to 5 so we can get the missing subgrades by getting it's grade adding 5 to it.
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i+'5',
                                      loan_data_strings[:,4])

In [47]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
# replaing the remaining missing values with a new subgrade H1
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                  'H1',
                                  loan_data_strings[:,4])

In [49]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [50]:
# now the subgrade column contains the grade column value plus the subgrade so we no longer need the grade column
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [51]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [52]:
loan_data_strings_header = np.delete(loan_data_strings_header,3)

In [53]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Converting Sub Grade

In [54]:
np.unique(loan_data_strings[:,3]).size

36

In [55]:
keys = list(np.unique(loan_data_strings[:,3]))                        
values = list(range(1,len(np.unique(loan_data_strings[:,3]))+1))
dict_sub_grade = dict(zip(keys,values))

In [56]:
dict_sub_grade['A1']

1

In [57]:
for i in np.unique(loan_data_strings[:,3]):
        loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                          str(dict_sub_grade[i]),
                                          loan_data_strings[:,3])

In [58]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [59]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [60]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [61]:
# we will consider missing values and not verified as 0 the rest is 1
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'),
                                  0,
                                  1)

In [62]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [63]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [64]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [65]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
loan_data_strings[:,5]

C:\Users\Hamoud's\AppData\Local\Temp\ipykernel_14276\2129155544.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [66]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [67]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=int),loan_data_strings[:,5].astype(dtype=int))

True

In [68]:
# since the id column is exactly like the url column, we do not need the url column     
loan_data_strings = np.delete(loan_data_strings,5,axis= 1)
loan_data_strings_header = np.delete(loan_data_strings_header,5)

In [69]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [70]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

### State Address

In [71]:
loan_data_strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [72]:
loan_data_strings_header[5] = "state_address"

In [73]:
state_name, state_count = np.unique(loan_data_strings[:,5],return_counts= True)
state_count_sorted = np.argsort(-state_count)
state_name[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [74]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                  '0',
                                  loan_data_strings[:,5])

In [75]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [76]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west), '1', loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south), '2', loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest), '3', loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east), '4', loan_data_strings[:,5])

In [77]:
np.unique([loan_data_strings[:,5]],return_counts= True)

(array(['0', '1', '2', '3', '4'], dtype='<U69'),
 array([ 500, 2467, 3384, 1733, 1916]))

## Converting to Numbers

In [78]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [79]:
loan_data_strings = loan_data_strings.astype(dtype=int)

In [80]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [81]:
checkpoint_strings_2 = checkpoint("checkpoint-strings-2",loan_data_strings_header,loan_data_strings)

In [82]:
checkpoint_strings_2['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [83]:
checkpoint_strings_2['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [84]:
np.array_equal(loan_data_strings, checkpoint_strings_2['data'])

True

## Manipulating Numeric Columns

In [85]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [86]:
#checking for missing values
np.isnan(loan_data_numeric).sum()

np.int64(0)

### Substitute "Filler" Values

In [87]:
loan_data_numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [88]:
temporary_fill

np.float64(68616520.0)

In [89]:
np.isin(loan_data_numeric[:,0],temporary_fill)

array([False, False, False, ..., False, False, False])

In [90]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()
#thus there is no missing values for this columns

np.int64(0)

In [91]:
# since in our model we need to fill the missing values with worst outcome ,
# so for all the remain coumns we will fill it with max for each column and only the miumum for the funded_amnt column
loan_data_numeric_header[1] = 'loan_amount'
loan_data_numeric_header[2] = 'funded_amount'
loan_data_numeric_header[3] = 'interest_rate'
loan_data_numeric_header[5] = 'total_payments'
loan_data_numeric_header


array(['id', 'loan_amount', 'funded_amount', 'interest_rate', 'installment', 'total_payments'],
      dtype='<U19')

#### Temporary Stats

In [92]:
temporary_stats[:,numeric_columns] # this is to only access the temp stats for the numeric data

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [93]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  temporary_stats[0,numeric_columns[2]],
                                  loan_data_numeric[:,2])

In [94]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [95]:
loan_data_numeric_header

array(['id', 'loan_amount', 'funded_amount', 'interest_rate', 'installment', 'total_payments'],
      dtype='<U19')

In [96]:
numeric_columns
# the numeric columns hols the positions for the columns related to the numeric data, we use it to access these date in the teporary_stata as it holds all the columns for the raw_date.

array([ 0,  2,  4,  6,  7, 13])

In [97]:
#replacing all the missing values with max val for each column
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                  temporary_stats[2,numeric_columns[i]],
                                  loan_data_numeric[:,i])

In [98]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [99]:
eur_usd = np.genfromtxt(r"H:\Loan project\EUR-USD.csv", delimiter=",", skip_header= 1, autostrip= True, usecols= 3)
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [100]:
#checking the issue date column which will be used to assign the conversion rate eur-usd per month
np.unique(loan_data_strings[:,0])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
exchange_rate = loan_data_strings[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             eur_usd[i-1],
                             exchange_rate)    
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(eur_usd),
                         exchange_rate)


In [102]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [103]:
exchange_rate.shape

(10000,)

In [104]:
loan_data_numeric.shape

(10000, 6)

In [105]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [106]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [107]:
loan_data_numeric_header = np.concatenate((loan_data_numeric_header,np.array(['exchange_rate'])))
loan_data_numeric_header

array(['id', 'loan_amount', 'funded_amount', 'interest_rate', 'installment', 'total_payments',
       'exchange_rate'], dtype='<U19')

#### From USD to EUR

In [108]:
loan_data_numeric_header

array(['id', 'loan_amount', 'funded_amount', 'interest_rate', 'installment', 'total_payments',
       'exchange_rate'], dtype='<U19')

In [109]:
dollar_columns = [1,2,4,5] #these are the columns that are in dollars and need to apply the exchange rate to it.

In [110]:
loan_data_numeric[:,dollar_columns]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [111]:
loan_data_numeric.shape

(10000, 7)

In [112]:
for i in dollar_columns:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [113]:
loan_data_numeric.shape  #here we can see that 4 columns were added to our dataset

(10000, 11)

#### Expanding the header

In [114]:
header_additional = np.array([column_name + '_EUR' for column_name in loan_data_numeric_header[dollar_columns]])
header_additional

array(['loan_amount_EUR', 'funded_amount_EUR', 'installment_EUR', 'total_payments_EUR'],
      dtype='<U18')

In [115]:
loan_data_numeric_header = np.concatenate((loan_data_numeric_header,header_additional))
loan_data_numeric_header

array(['id', 'loan_amount', 'funded_amount', 'interest_rate', 'installment', 'total_payments',
       'exchange_rate', 'loan_amount_EUR', 'funded_amount_EUR', 'installment_EUR',
       'total_payments_EUR'], dtype='<U19')

In [116]:
loan_data_numeric_header[dollar_columns] = np.array([column_name + '_USD' for column_name in loan_data_numeric_header[dollar_columns]])
loan_data_numeric_header

array(['id', 'loan_amount_USD', 'funded_amount_USD', 'interest_rate', 'installment_USD',
       'total_payments_USD', 'exchange_rate', 'loan_amount_EUR', 'funded_amount_EUR',
       'installment_EUR', 'total_payments_EUR'], dtype='<U19')

In [117]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [118]:
loan_data_numeric_header = loan_data_numeric_header[columns_index_order]
loan_data_numeric_header

array(['id', 'loan_amount_USD', 'loan_amount_EUR', 'funded_amount_USD', 'funded_amount_EUR',
       'interest_rate', 'installment_USD', 'installment_EUR', 'total_payments_USD',
       'total_payments_EUR', 'exchange_rate'], dtype='<U19')

In [119]:
#rearranging the numeriuc data according to the new columns headers order 
loan_data_numeric = loan_data_numeric[:,columns_index_order]
loan_data_numeric[15]

array([41480201.  ,    12725.  ,    11749.5 ,    12725.  ,    11749.5 ,       17.86,      322.17,
            297.47,    14262.61,    13169.24,        1.08])

In [120]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate

In [121]:
loan_data_numeric_header

array(['id', 'loan_amount_USD', 'loan_amount_EUR', 'funded_amount_USD', 'funded_amount_EUR',
       'interest_rate', 'installment_USD', 'installment_EUR', 'total_payments_USD',
       'total_payments_EUR', 'exchange_rate'], dtype='<U19')

In [122]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [123]:
loan_data_numeric[:,5] = loan_data_numeric[:,6]/100

In [124]:
loan_data_numeric[:,5]

array([11.85,  9.39,  4.95, ..., 13.73,  3.54,  3.1 ])

In [125]:
loan_data_numeric_header

array(['id', 'loan_amount_USD', 'loan_amount_EUR', 'funded_amount_USD', 'funded_amount_EUR',
       'interest_rate', 'installment_USD', 'installment_EUR', 'total_payments_USD',
       'total_payments_EUR', 'exchange_rate'], dtype='<U19')

In [126]:
loan_data_numeric[1]

array([57693261.  ,    30000.  ,    27132.46,    30000.  ,    27132.46,        9.39,      938.57,
            848.86,     4679.7 ,     4232.39,        1.11])

### Checkpoint 2: Numeric

In [127]:
checkpoint_numeric = checkpoint("check-point-numeric",loan_data_numeric_header,loan_data_numeric)

In [129]:
checkpoint_numeric['header']

array(['id', 'loan_amount_USD', 'loan_amount_EUR', 'funded_amount_USD', 'funded_amount_EUR',
       'interest_rate', 'installment_USD', 'installment_EUR', 'total_payments_USD',
       'total_payments_EUR', 'exchange_rate'], dtype='<U19')

## Creating the "Complete" Dataset

In [130]:
loan_data_strings.shape

(10000, 6)

In [131]:
loan_data_numeric.shape

(10000, 11)

In [153]:
loan_data = np.hstack((loan_data_numeric,loan_data_strings))

In [154]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [155]:
np.isnan(loan_data).sum()

np.int64(0)

In [156]:
header_full = np.concatenate((loan_data_numeric_header,loan_data_strings_header))
header_full.shape

(17,)

## Sorting the New Dataset

In [157]:
# we will use the first column of the data the id column to sort the dataset
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [158]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [159]:
# we can check with argsort the the id column is ordered correctly 

np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Storing the New Dataset

In [160]:
loan_data = np.vstack((header_full, loan_data))

In [161]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')